### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by iFranticman** [AdvancedPlugins/Skills#19]
### Describe the bug

Errors all in console

### How to reproduce

Latest version

### Screenshots / Videos

[11:47:37 ERROR]: Could not pass event PlayerCommandPreprocessEvent to AdvancedSkills v1.0.0
java.util.concurrent.CompletionException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a strin
g but was BEGIN_ARRAY at line 42 column 9 path $.n
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 4
2 column 9 path $.n
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson
-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1075) ~[gson-2.10.1.jar:?]
        at AdvancedSkills-1.0.7.jar/net.advancedplugins.skills.data.types.FilePlayerDataStorage.lambda$loadPlayerData$0(FilePlay
erDataStorage.java:36) ~[AdvancedSkills-1.0.7.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 42 column 9 path $.n
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:836) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:588) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$24.read(TypeAdapters.java:581) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[g
son-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFact
ory.java:433) ~[gson-2.10.1.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[gson
-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1075) ~[gson-2.10.1.jar:?]
        at AdvancedSkills-1.0.7.jar/net.advancedplugins.skills.data.types.FilePlayerDataStorage.lambda$loadPlayerData$0(FilePlay
erDataStorage.java:36) ~[AdvancedSkills-1.0.7.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more

**Comment by Ynverxe** [comment]
Hi! It's possible that your playerData is corrupted.

Can you send me your playerData files (zipping the folder obviously) via dicord?

**Comment by iFranticman** [comment]
Sent askills 0024 and i updated to the lastest skills version and same issue

**Comment by iFranticman** [comment]
Any updates

**Comment by Ynverxe** [comment]
afaik this problem must be solved, but I'll take a look again. do you deleted your userData folder? corrupted data cannot be recovered.
