### ISSUE TITLE
A is null console error Plugin AdvancedSkills v1.0.0 generated an exception while executing task 14883

### ISSUE THREAD

**Issue by moonies44** [AdvancedPlugins/Skills#21]
### Describe the bug

console is posting error about a error

### How to reproduce

happens on bootup on console.

### Screenshots / Videos

Plugin AdvancedSkills v1.0.0 generated an exception while executing task 14883

### Server Log

https://mclo.gs/5EMrTiE

**Comment by moonies44** [comment]
[01:33:52 WARN]: [AdvancedSkills] Plugin AdvancedSkills v1.0.0 generated an exception while executing task 14883
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicLong.get()" because "this.A" is null
        at net.advancedplugins.skills.data.PlayerData.getLastAccessed(PlayerData.java:129) ~[AdvancedSkills-1.0.7.jar:?]
        at net.advancedplugins.skills.data.PlayerDataHandler.lambda$cleanupCache$0(PlayerDataHandler.java:70) ~[AdvancedSkills-1.0.7.jar:?]
        at java.util.concurrent.ConcurrentHashMap.removeEntryIf(ConcurrentHashMap.java:1640) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$EntrySetView.removeIf(ConcurrentHashMap.java:4839) ~[?:?]
        at net.advancedplugins.skills.data.PlayerDataHandler.cleanupCache(PlayerDataHandler.java:69) ~[AdvancedSkills-1.0.7.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:34:52 WARN]: [AdvancedSkills] Plugin AdvancedSkills v1.0.0 generated an exception while executing task 14883
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicLong.get()" because "this.A" is null
        at net.advancedplugins.skills.data.PlayerData.getLastAccessed(PlayerData.java:129) ~[AdvancedSkills-1.0.7.jar:?]
        at net.advancedplugins.skills.data.PlayerDataHandler.lambda$cleanupCache$0(PlayerDataHandler.java:70) ~[AdvancedSkills-1.0.7.jar:?]
        at java.util.concurrent.ConcurrentHashMap.removeEntryIf(ConcurrentHashMap.java:1640) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$EntrySetView.removeIf(ConcurrentHashMap.java:4839) ~[?:?]
        at net.advancedplugins.skills.data.PlayerDataHandler.cleanupCache(PlayerDataHandler.java:69) ~[AdvancedSkills-1.0.7.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-496]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by moonies44** [comment]
seems the spam in console is growing in severity
https://mclo.gs/yMjQYzI

**Comment by Ynverxe** [comment]
Hi! It's possible that your playerData is corrupted.

Can you send me your playerData files (zipping the folder obviously) via dicord?

**Comment by moonies44** [comment]
> Hi! It's possible that your playerData is corrupted.
> 
> Can you send me your playerData files (zipping the folder obviously) via dicord?

i can yes do you want me to open a ticket? if not, you can add me directly on discord at treasureislands or treasureislands#0

**Comment by moonies44** [comment]
[userData.zip](https://github.com/user-attachments/files/16806410/userData.zip)
or just use this dl

**Comment by moonies44** [comment]
i will also add this, /skills no longer works either

https://mclo.gs/xaUo1oj

**Comment by Ynverxe** [comment]
> i will also add this, /skills no longer works either
> 
> https://mclo.gs/xaUo1oj

This problem is also caused by data corruption. We are working to fix this problem.
