### ISSUE TITLE
Data Corruption again on update

### ISSUE THREAD

**Issue by Cryptics1999** [AdvancedPlugins/Skills#23]
### Describe the bug

31.08 08:12:24 [Server] ERROR Could not pass event EffectsActivateEvent to AdvancedSkills v1.0.9
31.08 08:12:24 [Server] INFO java.lang.NullPointerException: null
31.08 08:12:35 [Server] WARN Plugin AdvancedSkills v1.0.9 generated an exception while executing task 200
31.08 08:12:35 [Server] INFO java.lang.NullPointerException: Cannot invoke "java.util.concurrent.atomic.AtomicLong.get()" because "this.lastAccessed" is null
31.08 08:12:35 [Server] INFO at AdvancedSkills-1.0.9.jar/net.advancedplugins.skills.data.PlayerData.getLastAccessed(PlayerData.java:145) ~[AdvancedSkills-1.0.9.jar:?]
31.08 08:12:35 [Server] INFO at AdvancedSkills-1.0.9.jar/net.advancedplugins.skills.data.PlayerDataHandler.lambda$cleanupCache$1(PlayerDataHandler.java:75) ~[AdvancedSkills-1.0.9.jar:?]
31.08 08:12:35 [Server] INFO at java.base/java.util.concurrent.ConcurrentHashMap.removeEntryIf(ConcurrentHashMap.java:1640) ~[?:?]
31.08 08:12:35 [Server] INFO at java.base/java.util.concurrent.ConcurrentHashMap$EntrySetView.removeIf(ConcurrentHashMap.java:4839) ~[?:?]
31.08 08:12:35 [Server] INFO at AdvancedSkills-1.0.9.jar/net.advancedplugins.skills.data.PlayerDataHandler.cleanupCache(PlayerDataHandler.java:74) ~[AdvancedSkills-1.0.9.jar:?]
31.08 08:12:35 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
31.08 08:12:35 [Server] INFO at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2299-5c0d2f7]
31.08 08:12:35 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
31.08 08:12:35 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
31.08 08:12:35 [Server] INFO at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
31.08 08:12:35 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Im guessing with the new party system all old data is corrupted, any fix to this?

### How to reproduce

Create data before update

Update and this error

**Comment by Cryptics1999** [comment]
https://discord.com/channels/376425582139015168/1279354669633769472
