### ISSUE TITLE
max-active config

### ISSUE THREAD

**Issue by Kub999** [AdvancedPlugins/Skills#38]
### Describe the bug

Not working. It only allows you to have one at once even if you change the number to any other. IF you try to enable more than one will send you a crash.

### How to reproduce

max-active: any number more than 1 

### Screenshots / Videos

[22:28:33 WARN]: java.lang.NoSuchMethodException: org.bukkit.craftbukkit.inventory.CraftMetaColorableArmor.setEnchantmentGlintOverride(java.lang.Boolean)
[22:28:33 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2848)
[22:28:33 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredMethod(AbstractDefaultRulesReflectionProxy.java:95)
[22:28:33 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredMethod(Unknown Source)
[22:28:33 WARN]:        at AdvancedSkills-1.1.5.jar//net.advancedplugins.skills.impl.utils.ASManager.makeItemGlow(ASManager.java:1727)
[22:28:33 WARN]:        at AdvancedSkills-1.1.5.jar//net.advancedplugins.skills.impl.utils.ASManager.makeItemGlow(ASManager.java:1740)
[22:28:33 WARN]:        at AdvancedSkills-1.1.5.jar//net.advancedplugins.skills.menus.TalentsMenu.openInventory(TalentsMenu.java:89)
[22:28:33 WARN]:        at AdvancedSkills-1.1.5.jar//net.advancedplugins.skills.menus.TalentsMenu.openInventory(TalentsMenu.java:46)
[22:28:33 WARN]:        at AdvancedSkills-1.1.5.jar//net.advancedplugins.skills.menus.TalentsMenu.onClick(TalentsMenu.java:150)
[22:28:33 WARN]:        at AdvancedSkills-1.1.5.jar//net.advancedplugins.skills.menus.TalentsMenu.lambda$openInventory$1(TalentsMenu.java:100)
[22:28:33 WARN]:        at AdvancedSkills-1.1.5.jar//net.advancedplugins.skills.impl.utils.menus.AdvancedMenu.onClick(AdvancedMenu.java:122)
[22:28:33 WARN]:        at AdvancedSkills-1.1.5.jar//net.advancedplugins.skills.impl.utils.menus.AdvancedMenuClick.onClick(AdvancedMenuClick.java:29)
[22:28:33 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1056.execute(Unknown Source)
[22:28:33 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[22:28:33 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[22:28:33 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[22:28:33 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[22:28:33 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[22:28:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[22:28:33 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3122)
[22:28:33 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[22:28:33 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[22:28:33 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[22:28:33 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:28:33 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[22:28:33 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[22:28:33 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1537)
[22:28:33 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[22:28:33 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[22:28:33 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1514)
[22:28:33 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1507)
[22:28:33 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[22:28:33 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466)
[22:28:33 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473)
[22:28:33 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318)
[22:28:33 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[22:28:33 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### Server Log

N/A

**Comment by Ynverxe** [comment]
Hi! This error should be fixed in the next version!
