### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by frknmrl** [AdvancedPlugins/Skills#46]
### Describe the bug

[03:32:59 ERROR]: Could not pass event EffectsActivateEvent to AdvancedSkills v1.2.9
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.skills.classes.PlayerClass.getSkills()" because the return value of "net.advancedplugins.skills.classes.ClassesHandler.getClass(String)" is null
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.skills.SkillsHandler.processPoints(SkillsHandler.java:115) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.skills.SkillsHandler.processPointsAndShare(SkillsHandler.java:92) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.listeners.SkillsListener.onAbilitiesActivate(SkillsListener.java:53) ~[AdvancedSkills-1.2.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor960.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.impl.commons.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:80) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.impl.commons.effects.actions.ActionExecution.run(ActionExecution.java:65) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.impl.commons.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:84) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.impl.commons.effects.mechanics.triggers.internal.FallDamageTrigger.onDamage(FallDamageTrigger.java:36) ~[AdvancedSkills-1.2.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor916.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1189) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1092) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1247) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:2118) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.player.Player.causeFallDamage(Player.java:1739) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.level.block.Block.fallOn(Block.java:459) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1838) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:410) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.level.ServerPlayer.doCheckFallDamage(ServerPlayer.java:1648) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1593) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:105) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

### How to reproduce

[03:32:59 ERROR]: Could not pass event EffectsActivateEvent to AdvancedSkills v1.2.9
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.skills.classes.PlayerClass.getSkills()" because the return value of "net.advancedplugins.skills.classes.ClassesHandler.getClass(String)" is null
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.skills.SkillsHandler.processPoints(SkillsHandler.java:115) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.skills.SkillsHandler.processPointsAndShare(SkillsHandler.java:92) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.listeners.SkillsListener.onAbilitiesActivate(SkillsListener.java:53) ~[AdvancedSkills-1.2.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor960.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.impl.commons.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:80) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.impl.commons.effects.actions.ActionExecution.run(ActionExecution.java:65) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.impl.commons.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:84) ~[AdvancedSkills-1.2.9.jar:?]
        at AdvancedSkills-1.2.9.jar/net.advancedplugins.skills.impl.commons.effects.mechanics.triggers.internal.FallDamageTrigger.onDamage(FallDamageTrigger.java:36) ~[AdvancedSkills-1.2.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor916.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1209) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1199) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1189) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1092) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1247) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2327) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1488) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1002) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1205) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.LivingEntity.causeFallDamage(LivingEntity.java:2118) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.player.Player.causeFallDamage(Player.java:1739) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.level.block.Block.fallOn(Block.java:459) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.Entity.checkFallDamage(Entity.java:1838) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.world.entity.LivingEntity.checkFallDamage(LivingEntity.java:410) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.level.ServerPlayer.doCheckFallDamage(ServerPlayer.java:1648) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1593) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:34) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:105) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-122-4430e96]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by Ynverxe** [comment]
Hi! The error appears too frecuently? Do you know if the error happens with a specific skill or class?

**Comment by Ynverxe** [comment]
Do you remember changing the name of / deleting a class? Seems that the error occurs because the player has an invalid class identifier, that could happen if the player chose a class and later that class was removed or the name changed.

**Comment by frknmrl** [comment]
> Do you remember changing the name of / deleting a class? Seems that the error occurs because the player has an invalid class identifier, that could happen if the player chose a class and later that class was removed or the name changed.

I changed the class names, will it be fixed if I delete the userData folder?

It also happens when the player takes damage from another player.

**Comment by Ynverxe** [comment]
This bug isn't solved by the moment but the error will be patched in the next release.

**Comment by GC-spigot** [comment]
Solved
