### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by XavierFunez** [AdvancedPlugins/Skills#47]
### Describe the bug

[20:53:35 ERROR]: Something went wrong while creating an item! Specified material doesn't exist! File: config  Config Path:   Value: CALIBRATED_SCULK_SENSOR
[20:53:36 INFO]: ï¿½cFailed to match 'CALIBRATED_SCULK_SENSOR' material, check your configuration or use https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html  to find needed material. ï¿½7ï¿½oFurther information has been pasted to console...
[20:53:36 WARN]: java.lang.IllegalArgumentException: Material cannot be null
[20:53:36 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
[20:53:36 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:98)
[20:53:36 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:86)
[20:53:36 WARN]:        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:73)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.ASManager.matchMaterial(ASManager.java:949)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.ASManager.matchMaterial(ASManager.java:952)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.ASManager.matchMaterial(ASManager.java:918)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.items.ConfigItemCreator.fromConfigSection(ConfigItemCreator.java:256)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.menus.item.AdvancedMenuItem.getItem(AdvancedMenuItem.java:97)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.menus.item.AdvancedMenuItem.addToInventory(AdvancedMenuItem.java:73)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.menus.AdvancedMenu.lambda$openInventory$0(AdvancedMenu.java:106)
[20:53:36 WARN]:        at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.menus.AdvancedMenu.openInventory(AdvancedMenu.java:104)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.menus.ProgressMenu.openInventory(ProgressMenu.java:79)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.menus.AdvancedMenusHandler.lambda$loadDefaultActions$2(AdvancedMenusHandler.java:42)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.menus.AdvancedMenu.onClick(AdvancedMenu.java:138)
[20:53:36 WARN]:        at AdvancedSkills-1.2.9.jar//net.advancedplugins.skills.impl.utils.menus.AdvancedMenuClick.onClick(AdvancedMenuClick.java:29)
[20:53:36 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor451.execute(Unknown Source)
[20:53:36 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[20:53:36 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[20:53:36 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[20:53:36 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[20:53:36 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[20:53:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[20:53:36 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3292)
[20:53:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[20:53:36 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[20:53:36 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[20:53:36 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:53:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:53:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:53:36 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1369)
[20:53:36 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[20:53:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[20:53:36 WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1346)
[20:53:36 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1339)
[20:53:36 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[20:53:36 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1317)
[20:53:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1205)
[20:53:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[20:53:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[20:53:36 ERROR]: Something went wrong while creating an item! Specified material doesn't exist! File: config  Config Path:   Value: CALIBRATED_SCULK_SENSOR

### How to reproduce

idk

**Comment by Ynverxe** [comment]
What is your server version?

**Comment by Ynverxe** [comment]
Probably your server version is outdated. Calibrated skull sensors were introduced in 1.20.

Change CALIBRATED_SKULL_SENSOR to other material.

Materials list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
