### ISSUE TITLE
Another console error

### ISSUE THREAD

**Issue by XavierFunez** [AdvancedPlugins/Skills#48]
### Describe the bug

[22:51:20] [Server thread/ERROR]: Could not pass event EffectsActivateEvent to AdvancedSkills v1.3.0
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.skills.classes.PlayerClass.getSkills()" because the return value of "net.advancedplugins.skills.classes.ClassesHandler.getClass(String)" is null
	at net.advancedplugins.skills.skills.SkillsHandler.processPoints(SkillsHandler.java:115) ~[AdvancedSkills-1.3.0.jar:?]
	at net.advancedplugins.skills.skills.SkillsHandler.processPointsAndShare(SkillsHandler.java:92) ~[AdvancedSkills-1.3.0.jar:?]
	at net.advancedplugins.skills.listeners.SkillsListener.onAbilitiesActivate(SkillsListener.java:53) ~[AdvancedSkills-1.3.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor498.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1985]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.advancedplugins.skills.impl.commons.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:80) ~[AdvancedSkills-1.3.0.jar:?]
	at net.advancedplugins.skills.impl.commons.effects.actions.ActionExecution.run(ActionExecution.java:65) ~[AdvancedSkills-1.3.0.jar:?]
	at net.advancedplugins.skills.impl.commons.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:84) ~[AdvancedSkills-1.3.0.jar:?]
	at net.advancedplugins.skills.impl.commons.effects.mechanics.triggers.internal.ElytraFlyTrigger.onFly(ElytraFlyTrigger.java:37) ~[AdvancedSkills-1.3.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor446.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1985]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callToggleGlideEvent(CraftEventFactory.java:1763) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.world.entity.player.Player.startFallFlying(Player.java:1824) ~[?:?]
	at net.minecraft.world.entity.player.Player.tryToStartFallFlying(Player.java:1814) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerCommand(ServerGamePacketListenerImpl.java:2805) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerCommandPacket.handle(ServerboundPlayerCommandPacket.java:13) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

### How to reproduce

/skills

**Comment by GC-spigot** [comment]
Solved
